apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: sonarr-build-template
metadata:
  annotations:
  name: sonarr-build
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: ${BASE_NAME}
      labels:
        build: ${BASE_NAME}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: source
          from:
            kind: ${IMAGE_SOURCE_KIND}
            name: ${IMAGE_SOURCE_NAME}
          importPolicy:
            scheduled: true
          referencePolicy:
            type: Local
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: ${BASE_NAME}-${ID}
      labels:
        build: ${BASE_NAME}
    spec:
      output:
        to:
          kind: ${BUILD_OUTPUT_KIND}
          name: "${BUILD_OUTPUT_NAME}:${SONARR_VERSION}"
        pushSecret:
          name: ${BUILD_OUTPUT_SECRET}
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          buildArgs:
            - name: SONARR_VERSION
              value: ${SONARR_VERSION}
          from:
            kind: ImageStreamTag
            name: '${BASE_NAME}:source'
      postCommit:
        script: '/sonarr/test.sh'
      source:
        type: Git
        git:
          uri: ${GIT_SOURCE_URL}
          ref: ${GIT_SOURCE_REF}
      triggers:
        - type: ConfigChange
        - type: ImageChange
      runPolicy: Serial
parameters:
  - name: IMAGE_SOURCE_NAME
    required: true
    value: "ubuntu:rolling"
  - name: IMAGE_SOURCE_KIND
    required: true
    value: DockerImage
  - name: BUILD_OUTPUT_NAME
    required: true
    value: "quay.io/parflesh/sonarr"
  - name: BUILD_OUTPUT_KIND
    required: true
    value: DockerImage
  - name: BUILD_OUTPUT_SECRET
    required: true
    value: image-push-secret
  - name: GIT_SOURCE_URL
    required: true
    value: "https://github.com/ParFlesh/sonarr.git"
  - name: GIT_SOURCE_REF
  - name: BASE_NAME
    required: true
    value: sonarr
  - name: ID
    required: true
    value: "latest"
  - name: SONARR_VERSION
    value: "latest"