name: Build Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

env:
  TEST_TAG: parflesh/sonarr:test
  PUSH_TAG: quay.io/parflesh/sonarr:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: ${{ env.TEST_TAG }}
    - name: Test
      id: docker_test
      run: |
        docker run --entrypoint /usr/bin/bash --rm ${{ env.TEST_TAG }} /test.sh
    - name: Docker Login
      id: docker_login
      uses: docker/login-action@v1.10.0
      with:
        registry: quay.io
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push
      id: docker_push
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64
        tags: ${{ env.PUSH_TAG }}
